import 'package:flutter/material.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedNearestHospitalWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedEmergencyResourcesWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedCurrentLocationWidget2.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/Generated9999999999Widget1.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedNearestRedCrossShelterWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedLocalResourcesWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedGroup4Widget5.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedLocalFireDepartmentWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedLocalPoliceDepartmentWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/Generated9999999999Widget2.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/Generated9999999999Widget3.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedMapWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/Generated9999999999Widget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedTrafficEvacMapWidget.dart';
import 'package:flutterapp/safeprepapp/generatedemergencyaccesstabwidget/generated/GeneratedNavBarWidget4.dart';

/* Frame Emergency Access Tab
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmergencyAccessTabWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 901.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 901.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 207.0,
                              height: 50.0,
                              child: GeneratedEmergencyResourcesWidget(),
                            ),
                            Positioned(
                              left: 206.5,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 0.6265316605567932,
                              height: 49.49606704711914,
                              child: GeneratedVector1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 207.0,
                              height: 50.0,
                              child: GeneratedRectangle13Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 479.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 21.0,
                              child: GeneratedLocalResourcesWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 313.0,
                              child: GeneratedMapWidget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 543.0,
                              right: null,
                              bottom: null,
                              width: 185.0,
                              height: 23.0,
                              child: GeneratedLocalFireDepartmentWidget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 23.0,
                              child: GeneratedNearestHospitalWidget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 204.0,
                              height: 23.0,
                              child: GeneratedLocalPoliceDepartmentWidget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 666.0,
                              right: null,
                              bottom: null,
                              width: 153.0,
                              height: 44.0,
                              child: GeneratedNearestRedCrossShelterWidget(),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 543.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 26.0,
                              child: Generated9999999999Widget(),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 26.0,
                              child: Generated9999999999Widget1(),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 26.0,
                              child: Generated9999999999Widget2(),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 687.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 26.0,
                              child: Generated9999999999Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.5024154589371981;

                                final double height =
                                    constraints.maxHeight * 0.05327413984461709;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.42028985507246375,
                                      y: constraints.maxHeight *
                                          0.042175360710321866,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedCurrentLocationWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 157.0,
                              height: 17.0,
                              child: GeneratedTrafficEvacMapWidget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 50.27272415161133,
                              height: 49.0,
                              child: GeneratedGroup4Widget5(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 0.0,
                              width: 414.0,
                              height: 85.0,
                              child: GeneratedNavBarWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
